/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: d6fdc0a953ffc12f6e4db5088edd85a7)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		DB: D1Database;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
