/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: 2b4e90cf0ea0d5faf37adc284cfafbb5)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_TEST_MODE: string;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		TURNSTILE_SECRET_KEY: string;
		TURNSTILE_TEST_MODE: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SECRET_KEY" | "TURNSTILE_TEST_MODE">> {}
}
