/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: 9a543c307684c1d05524b4d0f118d191)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	TURNSTILE_SECRET_KEY: string;
	IP_HASH_SALT: string;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		DB: D1Database;
		TURNSTILE_SECRET_KEY: string;
		IP_HASH_SALT: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURNSTILE_SECRET_KEY" | "IP_HASH_SALT">> {}
}
