import { Check, MessageCircle, Phone } from "lucide-react";
import { JsonLd } from "@/components/JsonLd";
import { SiteShell } from "@/components/site/SiteShell";
import { TrackedLink } from "@/components/TrackedLink";
import { PageHero } from "@/components/ui/PageHero";
import staticPages from "@/content/settings/static-pages.json";
import { PHONE_DISPLAY, PHONE_HREF, ZALO_URL, breadcrumbSchema, createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Trao đổi vật liệu gỗ và gia công CNC", description: "Gọi điện hoặc nhắn Zalo để trao đổi trực tiếp về vật liệu gỗ, quy cách và yêu cầu gia công CNC.", path: "/bao-gia", noIndex: true });
const checklist = ["Loại vật liệu hoặc mã đang quan tâm.", "Kích thước, độ dày và số lượng.", "Yêu cầu bề mặt, cạnh hoặc CNC.", "Khu vực nhận hàng hoặc hình thức bàn giao cần trao đổi."];

export default function QuotePage() {
  return <><JsonLd data={breadcrumbSchema([{ name: "Trang chủ", path: "/" }, { name: "Liên hệ trực tiếp", path: "/bao-gia" }])} /><SiteShell><PageHero compact breadcrumbs={[{ label: "Trang chủ", href: "/" }, { label: "Liên hệ trực tiếp" }]} eyebrow="Kênh liên hệ không qua form" title="Trao đổi vật liệu và gia công CNC" description={staticPages.quoteIntro} /><section className="section-space bg-[#f7f8f5]"><div className="container-shell grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="border border-forest-900/10 bg-white p-7"><h2 className="text-2xl font-extrabold text-forest-950">Thông tin nên chuẩn bị</h2><ul className="mt-6 space-y-4">{checklist.map((item) => <li key={item} className="flex gap-3 text-sm leading-7 text-slate-700"><Check size={18} className="mt-1 shrink-0 text-wood-600" aria-hidden="true" />{item}</li>)}</ul></div><div className="border border-forest-900/10 bg-[#edf4ef] p-7 sm:p-9"><h2 className="text-2xl font-extrabold text-forest-950">Liên hệ Tùng Phát</h2><p className="mt-4 leading-7 text-slate-700">Website không nhận form báo giá hoặc tải file trực tiếp. Vui lòng gọi điện hoặc nhắn Zalo để kiểm tra đúng thông tin thực tế.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><TrackedLink href={PHONE_HREF} eventName="click_phone" eventProperties={{ location: "legacy_quote_page" }} className="pressable inline-flex min-h-14 items-center justify-center gap-2 bg-wood-500 px-7 text-sm font-extrabold text-white"><Phone size={18} aria-hidden="true" />Gọi {PHONE_DISPLAY}</TrackedLink><TrackedLink href={ZALO_URL} target="_blank" rel="noopener noreferrer" eventName="click_zalo" eventProperties={{ location: "legacy_quote_page" }} className="pressable inline-flex min-h-14 items-center justify-center gap-2 border border-forest-900/20 bg-white px-7 text-sm font-extrabold text-forest-950"><MessageCircle size={18} aria-hidden="true" />Nhắn Zalo</TrackedLink></div></div></div></section></SiteShell></>;
}
