import { cloudflare } from "@cloudflare/vite-plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react(), cloudflare({ configPath: "./wrangler.worker.jsonc" })],
  // Client source maps expose the entire internal editor to public assets.
  // Worker maps are still generated by Wrangler for observability.
  build: { sourcemap: false },
});
