import { useEffect, useState } from "react";
import { api } from "../api";
import { StatePanel } from "../components/StatePanel";
import { lightCmsUiCopy } from "../environment";

export function ContentScreen({ collection }: { collection: string }) {
  const [items, setItems] = useState<Array<{ id: string; title: string; slug: string; status: string; version: number; updatedAt: string }>>([]); const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const [json, setJson] = useState(""); const [status, setStatus] = useState<"draft" | "published">("draft"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { setSelected(null); setError(""); api.list(collection).then((data) => setItems(data.items)).catch((reason: Error) => setError(reason.message)); }, [collection]);
  async function open(id: string) { try { const detail = await api.detail(collection, id); setSelected(detail); const parsed = typeof detail.content_json === "string" ? JSON.parse(detail.content_json) as Record<string, unknown> : detail; setJson(JSON.stringify(parsed, null, 2)); setStatus(detail.status === "published" ? "published" : "draft"); } catch (reason) { setError((reason as Error).message); } }
  async function save() { if (!selected) return; setMessage(""); try { const data = JSON.parse(json) as unknown; await api.save(collection, String(selected.id), data, Number(selected.version), status); setMessage("Đã lưu nội dung. Tải lại danh sách để xem version mới."); } catch (reason) { setError((reason as Error).message); } }
  if (error && !items.length && !selected) return <StatePanel title="Không tải được nội dung" description={error} tone="error" />;
  return <><header className="page-heading"><p className="eyebrow">THƯ VIỆN NỘI DUNG</p><h1>{collection}</h1><p>Danh sách chỉ tải cột tóm tắt; JSON đầy đủ chỉ được đọc khi mở bản ghi.</p></header><div className="editor-layout"><section className="list-panel"><h2>Danh sách</h2>{items.length ? <ul className="content-list">{items.map((item) => <li key={item.id}><button onClick={() => open(item.id)}><strong>{item.title}</strong><span>{item.slug}</span><small>{item.status} · v{item.version}</small></button></li>)}</ul> : <StatePanel title="Chưa có nội dung" description={lightCmsUiCopy.contentEmpty} />}</section><section className="editor-panel">{selected ? <><div className="editor-toolbar"><div><p className="eyebrow">CHỈNH SỬA</p><h2>{String(selected.title || "Bản ghi")}</h2></div><label>Trạng thái<select value={status} onChange={(event) => setStatus(event.target.value as "draft" | "published")}><option value="draft">Bản nháp</option><option value="published">Xuất bản</option></select></label></div><label className="editor-field">Dữ liệu nội dung<textarea rows={24} value={json} onChange={(event) => setJson(event.target.value)} spellCheck={false} /></label>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<div className="action-row"><button className="primary" onClick={save}>Lưu thay đổi</button><button onClick={() => setSelected(null)}>Đóng</button></div></> : <StatePanel title="Chọn một bản ghi" description="Nội dung chi tiết và version sẽ hiển thị tại đây." />}</section></div></>;
}
