import { useEffect, useState } from "react";
import { api } from "../api";
import { StatePanel } from "../components/StatePanel";

export function SettingsScreen({ setting }: { setting: string }) {
  const [activeSetting, setActiveSetting] = useState(setting);
  const [json, setJson] = useState(""); const [version, setVersion] = useState(0); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { setJson(""); setError(""); setMessage(""); void api.settings(activeSetting).then((result) => { setJson(JSON.stringify(result.data, null, 2)); setVersion(result.version); }).catch((reason: Error) => setError(reason.message)); }, [activeSetting]);
  async function save() { try { await api.saveSettings(activeSetting, JSON.parse(json), version); setVersion((value) => value + 1); setMessage("Đã lưu cài đặt."); } catch (reason) { setError((reason as Error).message); } }
  if (!json && error) return <StatePanel title="Chưa tải được setting" description={error} tone="error" />;
  return <><header className="page-heading"><p className="eyebrow">CẤU HÌNH</p><h1>Cài đặt</h1><p>Quản lý thông tin doanh nghiệp và cấu hình SEO mặc định tại một nơi.</p></header><div className="settings-tabs" role="tablist" aria-label="Nhóm cài đặt"><button type="button" role="tab" aria-selected={activeSetting === "business-settings"} className={activeSetting === "business-settings" ? "active" : ""} onClick={() => setActiveSetting("business-settings")}>Thông tin doanh nghiệp</button><button type="button" role="tab" aria-selected={activeSetting === "seo-defaults"} className={activeSetting === "seo-defaults" ? "active" : ""} onClick={() => setActiveSetting("seo-defaults")}>SEO mặc định</button></div><section className="editor-panel standalone settings-editor"><div className="section-heading-row"><div><h2>{activeSetting === "business-settings" ? "Thông tin doanh nghiệp" : "SEO mặc định"}</h2><p>Dữ liệu được kiểm tra bằng schema dùng chung trước khi lưu.</p></div><span className="version-chip">Phiên bản {version}</span></div><label className="editor-field">Dữ liệu JSON<textarea rows={24} value={json} onChange={(event) => setJson(event.target.value)} spellCheck={false} /></label>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<button className="button primary" onClick={save}>Lưu cài đặt</button></section></>;
}
