import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`media_legacy_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`media\` DROP COLUMN \`legacy_path\`;`)
  await db.run(sql`DROP INDEX \`products_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`products\` DROP COLUMN \`legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`_products_v_version_version_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`_products_v\` DROP COLUMN \`version_legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`_products_v\` DROP COLUMN \`version_legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`articles_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`articles\` DROP COLUMN \`legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`articles\` DROP COLUMN \`legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`_articles_v_version_version_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`_articles_v\` DROP COLUMN \`version_legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`_articles_v\` DROP COLUMN \`version_legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`projects_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`projects\` DROP COLUMN \`legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`projects\` DROP COLUMN \`legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`_projects_v_version_version_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v\` DROP COLUMN \`version_legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v\` DROP COLUMN \`version_legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`pages_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`pages\` DROP COLUMN \`legacy_checksum\`;`)
  await db.run(sql`DROP INDEX \`_pages_v_version_version_legacy_source_path_idx\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_legacy_source_path\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` DROP COLUMN \`version_legacy_checksum\`;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`media\` ADD \`legacy_path\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`media_legacy_path_idx\` ON \`media\` (\`legacy_path\`);`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`products\` ADD \`legacy_checksum\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`products_legacy_source_path_idx\` ON \`products\` (\`legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`_products_v\` ADD \`version_legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`_products_v\` ADD \`version_legacy_checksum\` text;`)
  await db.run(sql`CREATE INDEX \`_products_v_version_version_legacy_source_path_idx\` ON \`_products_v\` (\`version_legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`articles\` ADD \`legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`articles\` ADD \`legacy_checksum\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`articles_legacy_source_path_idx\` ON \`articles\` (\`legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`_articles_v\` ADD \`version_legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`_articles_v\` ADD \`version_legacy_checksum\` text;`)
  await db.run(sql`CREATE INDEX \`_articles_v_version_version_legacy_source_path_idx\` ON \`_articles_v\` (\`version_legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`projects\` ADD \`legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`projects\` ADD \`legacy_checksum\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`projects_legacy_source_path_idx\` ON \`projects\` (\`legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`_projects_v\` ADD \`version_legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`_projects_v\` ADD \`version_legacy_checksum\` text;`)
  await db.run(sql`CREATE INDEX \`_projects_v_version_version_legacy_source_path_idx\` ON \`_projects_v\` (\`version_legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`legacy_checksum\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`pages_legacy_source_path_idx\` ON \`pages\` (\`legacy_source_path\`);`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_legacy_source_path\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v\` ADD \`version_legacy_checksum\` text;`)
  await db.run(sql`CREATE INDEX \`_pages_v_version_version_legacy_source_path_idx\` ON \`_pages_v\` (\`version_legacy_source_path\`);`)
}
