import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { MaterialSelector } from "@/components/materials/MaterialSelector";
import { MaterialReferenceTable } from "@/components/materials/MaterialReferenceTable";
import { JsonLd } from "@/components/JsonLd";
import { SiteShell } from "@/components/site/SiteShell";
import { ContactCTA } from "@/components/ui/ContactCTA";
import { PageHero } from "@/components/ui/PageHero";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { getMaterialDataset } from "@/lib/materials";
import { getMaterialComparisonMatrix } from "@/lib/material-reference";
import { absolutePageUrl, absoluteUrl, breadcrumbSchema, createPageMetadata, schemaPageId, webPageSchema } from "@/lib/seo";

const pagePath = "/tham-chieu-vat-lieu";
export const metadata = createPageMetadata({
  title: "Tham chiếu vật liệu MDF, gỗ ghép và CNC",
  description: "Bảng tham chiếu vật liệu Tùng Phát: dữ liệu đã kiểm tra, điểm còn cần xác nhận, so sánh MDF thường và MDF chống ẩm, cùng bộ chọn vật liệu định hướng.",
  path: pagePath,
});

export default function MaterialReferencePage() {
  const dataset = getMaterialDataset();
  const comparisonMatrix = getMaterialComparisonMatrix();
  const referenceId = schemaPageId(pagePath, "dataset");
  const mdf = dataset.materials.find((material) => material.slug === "van-mdf");
  const moistureMdf = dataset.materials.find((material) => material.slug === "mdf-chong-am");
  return (
    <>
      <JsonLd data={[
        webPageSchema({ path: pagePath, name: "Tham chiếu vật liệu MDF, gỗ ghép và CNC", description: metadata.description as string, type: "CollectionPage", primaryEntityId: referenceId, dateModified: dataset.lastVerified }),
        breadcrumbSchema([{ name: "Trang chủ", path: "/" }, { name: "Tham chiếu vật liệu", path: pagePath }]),
        { "@context": "https://schema.org", "@type": "Dataset", "@id": referenceId, name: "Bộ dữ liệu tham chiếu và ma trận so sánh vật liệu Tùng Phát", description: dataset.description, url: absolutePageUrl(pagePath), inLanguage: "vi-VN", dateModified: dataset.lastVerified, creator: { "@id": schemaPageId("/", "organization") }, version: dataset.schemaVersion, isAccessibleForFree: true, distribution: [{ "@type": "DataDownload", encodingFormat: "text/csv", contentUrl: absoluteUrl("/material-comparison-matrix.csv") }, { "@type": "DataDownload", encodingFormat: "application/json", contentUrl: absoluteUrl("/material-comparison-matrix.json") }] },
      ]} />
      <SiteShell>
        <PageHero breadcrumbs={[{ label: "Trang chủ", href: "/" }, { label: "Tham chiếu vật liệu" }]} eyebrow="Dữ liệu kỹ thuật có nguồn" title="Tham chiếu vật liệu để chọn và gửi yêu cầu rõ hơn" description="Một bảng dữ liệu nhỏ, có nguồn và có ngày kiểm tra. Tùng Phát chỉ công bố các nhận định đã có trong nội dung hiện tại; kích thước, độ dày, mã hàng và tồn kho chưa được xác minh sẽ để trống." />
        <section data-answer-block className="border-b border-forest-900/10 bg-[#edf4ef] py-8" aria-labelledby="reference-answer-title"><div className="container-shell max-w-4xl"><p className="eyebrow">Trả lời nhanh</p><h2 id="reference-answer-title" className="mt-3 text-2xl font-extrabold text-forest-950">Nên chọn vật liệu nào trước?</h2><p className="mt-3 text-base leading-8 text-slate-700">Bắt đầu bằng hạng mục, môi trường, bề mặt và yêu cầu CNC. MDF chống ẩm chỉ là hướng cân nhắc cho nơi ẩm hơn phòng khô, không phải cam kết chống nước; gỗ ghép cao su hoặc tràm phù hợp khi thiết kế cần bề mặt gỗ tự nhiên và có thể đối chiếu mẫu/lô hàng.</p></div></section>
        <section className="section-space bg-white"><div className="container-shell"><SectionHeader eyebrow="Bảng tham chiếu" title="Dữ liệu hiện có và điểm cần xác nhận" description={`Cập nhật dữ liệu: ${dataset.lastVerified}. Null không phải giá trị ước đoán; đó là dấu hiệu cần kiểm tra catalogue, mẫu hoặc mã hàng trước khi báo giá.`} /><div className="mt-8"><MaterialReferenceTable materials={dataset.materials} sources={dataset.sources} categories={[...new Set(dataset.materials.map((material) => material.category))]} lastVerified={dataset.lastVerified} /></div><p className="mt-5 text-sm text-slate-600">Tải dữ liệu: <a href="/material-reference.csv" className="font-bold text-wood-600 underline">bảng tham chiếu CSV</a>. Bản ghi cấp gia đình không xác nhận Tùng Phát đang có tồn kho mã hàng cụ thể.</p></div></section>
        <section className="section-space bg-[#f7f8f5]" aria-labelledby="comparison-matrix-title"><div className="container-shell"><SectionHeader eyebrow="Dữ liệu gốc có nguồn" title="Ma trận so sánh vật liệu đã kiểm chứng" description="Sáu nhóm được so sánh theo cùng cấu trúc. Ô chưa đủ bằng chứng được giữ trống; không có kết luận vật liệu nào luôn tốt hơn." /><div className="mt-8 overflow-x-auto"><table className="min-w-[1180px] w-full border-collapse text-left text-sm"><caption className="sr-only">Ma trận so sánh MDF, MDF chống ẩm, HDF, MFC, plywood và gỗ ghép</caption><thead><tr className="border-b border-forest-900/15 text-xs uppercase tracking-wide text-slate-500"><th className="p-3">Nhóm</th><th className="p-3">Cấu tạo</th><th className="p-3">Mật độ</th><th className="p-3">Ẩm</th><th className="p-3">Gia công</th><th className="p-3">Bề mặt</th><th className="p-3">Khi cân nhắc</th></tr></thead><tbody>{comparisonMatrix.map((row) => <tr id={`comparison-${row.id}`} key={row.id} className="scroll-mt-28 border-b border-forest-900/10 align-top"><th scope="row" className="p-3 font-extrabold text-forest-950"><a href={`#comparison-${row.id}`} className="underline decoration-wood-400 underline-offset-4">{row.name}</a></th><td className="p-3 text-slate-700">{row.composition ?? "Chưa xác minh"}</td><td className="p-3 text-slate-700">{row.density ?? "Chưa xác minh"}</td><td className="p-3 text-slate-700">{row.moistureBehavior ?? "Chưa xác minh"}</td><td className="p-3 text-slate-700">{row.machining ?? "Chưa xác minh"}</td><td className="p-3 text-slate-700">{row.surfaceFinish ?? "Chưa xác minh"}</td><td className="p-3 text-slate-700">{row.choiceGuidance ?? "Chưa xác minh"}<span className="mt-2 block text-[11px] uppercase tracking-wide text-slate-500">Nguồn: {row.sourceIds.map((sourceId, index) => { const source = dataset.sources.find((item) => item.id === sourceId); return source ? <span key={sourceId}>{index ? " · " : ""}<a href={source.sourceUrl} rel="noreferrer" className="font-bold text-wood-600 underline normal-case tracking-normal">{source.sourceTitle}</a></span> : sourceId; })}</span></td></tr>)}</tbody></table></div><p className="mt-5 text-sm text-slate-600">Tải ma trận: <a href="/material-comparison-matrix.csv" className="font-bold text-wood-600 underline">CSV</a> · <a href="/material-comparison-matrix.json" className="font-bold text-wood-600 underline">JSON có cả bản ghi nguồn</a>.</p></div></section>
        <section className="section-space bg-white"><div className="container-shell"><SectionHeader eyebrow="Ba câu hỏi so sánh" title="MDF khác plywood, MFC và HDF ở đâu?" description="Câu trả lời ngắn dùng định nghĩa cùng nguồn; lựa chọn cuối cùng vẫn phụ thuộc cấp sản phẩm, môi trường, bề mặt và kết cấu." /><div className="mt-8 grid gap-5 lg:grid-cols-3">{[{q:"MDF hay plywood?",a:"MDF dùng sợi gỗ liên kết bằng nhựa và có bề mặt đồng nhất; plywood dùng các lớp veneer, thớ lớp kề thường vuông góc. Chọn theo nhu cầu bề mặt đồng nhất/gia công hay cấu trúc veneer ghép lớp và đúng cấp sử dụng.",s:"EPF MDF + EPF Plywood"},{q:"MDF hay MFC?",a:"MDF mô tả cốt fibreboard. MFC là particleboard phủ melamine theo nguồn An Cường được dẫn. Vì một bên là cốt, một bên là tấm đã có bề mặt trang trí, cần so đúng cốt, lớp phủ và cạnh thay vì kết luận loại nào luôn tốt hơn.",s:"EPF MDF + EPF Particleboard + An Cường MFC"},{q:"MDF hay HDF?",a:"EPF xếp HDF là biến thể MDF mật độ cao: HDF trên 800 kg/m3, trong khi MDF trung bình điển hình 700-800 kg/m3. Khoảng này là phân loại tham chiếu, không thay thế datasheet từng mã hoặc tự chứng minh khả năng chống ẩm.",s:"EPF MDF"}].map((item)=><article data-answer-block key={item.q} className="rounded-2xl border border-forest-900/10 bg-[#f7f8f5] p-6"><h3 className="text-xl font-extrabold text-forest-950">{item.q}</h3><p className="mt-3 leading-7 text-slate-700">{item.a}</p><p className="mt-4 text-xs font-bold uppercase tracking-wide text-slate-500">Nguồn: {item.s} · kiểm tra {dataset.lastVerified}</p></article>)}</div><div className="mt-5 flex flex-wrap gap-3 text-sm"><Link href={mdf?.detailUrl ?? "/van-mdf/"} className="inline-flex items-center gap-2 font-extrabold text-wood-600">Xem trang MDF <ArrowRight size={16} /></Link><Link href={moistureMdf?.detailUrl ?? "/mdf-chong-am/"} className="inline-flex items-center gap-2 font-extrabold text-wood-600">Xem MDF chống ẩm <ArrowRight size={16} /></Link></div></div></section>
        <section className="section-space bg-white"><div className="container-shell"><MaterialSelector /></div></section>
        <section id="methodology" className="border-y border-forest-900/10 bg-[#f7f8f5] py-10" aria-labelledby="material-methodology-title"><div className="container-shell"><p className="eyebrow">Minh bạch dữ liệu</p><h2 id="material-methodology-title" className="mt-3 text-2xl font-extrabold text-forest-950">Phương pháp và cách trích dẫn</h2><div className="mt-5 grid gap-4 text-sm leading-7 text-slate-700 md:grid-cols-2"><p><strong className="text-forest-950">Dữ liệu được đưa vào:</strong> định nghĩa cấp nhóm vật liệu, trường so sánh, nguồn và ngày kiểm tra. P1 là nguồn nhà sản xuất, P3 là dữ liệu kinh doanh first-party, P4 là nguồn kỹ thuật uy tín; không dùng P5 cho thông số công bố.</p><p><strong className="text-forest-950">Giá trị chưa biết:</strong> giữ <code>null</code> trong JSON và hiển thị “Chưa xác minh”, không nội suy từ ảnh, tên hàng hoặc kinh nghiệm chung.</p><p><strong className="text-forest-950">Dữ kiện nhà sản xuất:</strong> luôn đi kèm nguồn. <strong className="text-forest-950">Khuyến nghị của Tùng Phát:</strong> chỉ là hướng chọn và câu hỏi cần xác nhận, không thay thế datasheet, mẫu, mã hàng hoặc tình trạng tồn kho.</p><p><strong className="text-forest-950">Cách trích dẫn:</strong> dẫn trang này, ngày kiểm tra {dataset.lastVerified} và neo đúng hàng, ví dụ <code>/tham-chieu-vat-lieu/#comparison-family-mdf</code>. Có thể dùng CSV/JSON khi cần dữ liệu máy đọc.</p></div><ul className="mt-6 grid gap-2 text-sm text-slate-600 md:grid-cols-2">{dataset.sources.map((source)=><li key={source.id}><a href={source.sourceUrl} rel="noreferrer" className="font-bold text-wood-600 underline">{source.sourceTitle}</a> · {source.qualityTier}</li>)}</ul></div></section>
        <ContactCTA title="Đã có quy cách hoặc file cần kiểm tra?" description="Gửi hạng mục, môi trường, kích thước, độ dày, số lượng, bề mặt và yêu cầu CNC để Tùng Phát đối chiếu dữ liệu thực tế." />
      </SiteShell>
    </>
  );
}
