/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Ho_Chi_Minh';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    suppliers: Supplier;
    categories: Category;
    'material-codes': MaterialCode;
    products: Product;
    articles: Article;
    projects: Project;
    pages: Page;
    reviews: Review;
    'gbp-connections': GbpConnection;
    leads: Lead;
    'analytics-events': AnalyticsEvent;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'material-codes': MaterialCodesSelect<false> | MaterialCodesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'gbp-connections': GbpConnectionsSelect<false> | GbpConnectionsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'business-settings': BusinessSetting;
    'seo-defaults': SeoDefault;
    'static-pages': StaticPage;
    'material-categories': MaterialCategory;
    brands: Brand;
  };
  globalsSelect: {
    'business-settings': BusinessSettingsSelect<false> | BusinessSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    'material-categories': MaterialCategoriesSelect<false> | MaterialCategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Tài khoản quản trị Payload. Chỉ Super Admin được quản lý người dùng và phân quyền.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ảnh, video và catalogue dùng cho website. Hãy nhập alt text mô tả nội dung ảnh.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Mô tả ngắn nội dung và mục đích của ảnh; không bắt đầu bằng “Hình ảnh…”.
   */
  alt: string;
  caption?: string | null;
  mediaKind: 'content' | 'product' | 'project' | 'brand' | 'document' | 'video';
  uploadedBy?: (number | null) | User;
  r2Key?: string | null;
  sourceURL?: string | null;
  checksum?: string | null;
  roomApplication?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  key: string;
  name: string;
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  sourceURL?: string | null;
  enabled?: boolean | null;
  lastSyncedAt?: string | null;
  syncChecksum?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  supplier?: (number | null) | Supplier;
  parent?: (number | null) | Category;
  description?: string | null;
  sourceID?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-codes".
 */
export interface MaterialCode {
  id: number;
  stableKey: string;
  supplier: number | Supplier;
  code: string;
  name: string;
  slug: string;
  category?: (number | null) | Category;
  subcategory?: string | null;
  description?: string | null;
  materialType?: string | null;
  finish?: string | null;
  dimensions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  thicknesses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  applicationGallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  sourceURL?: string | null;
  sourceID?: string | null;
  syncChecksum?: string | null;
  lastSyncedAt?: string | null;
  status: 'published' | 'draft' | 'archived';
  /**
   * Thông tin dùng cho kết quả tìm kiếm và Open Graph. Không thay đổi SEO production trong bước này.
   */
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Vật liệu và sản phẩm đang được Tùng Phát giới thiệu trên website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  category: string;
  excerpt: string;
  materialType: string;
  /**
   * Không ghi đại lý chính thức nếu chưa có bằng chứng.
   */
  supplier?: string | null;
  thicknesses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  dimensions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  surfaces?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  standards?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  applications: {
    value: string;
    id?: string | null;
  }[];
  advantages: {
    value: string;
    id?: string | null;
  }[];
  limitations: {
    value: string;
    id?: string | null;
  }[];
  orderingSteps: {
    value: string;
    id?: string | null;
  }[];
  availability: 'available' | 'discontinued' | 'guide';
  quoteCta: string;
  relatedArticles?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown được giữ nguyên để tương thích dữ liệu và renderer hiện tại.
   */
  body: string;
  video?: (number | null) | Media;
  catalogue?: (number | null) | Media;
  /**
   * Chỉ chữ thường, số và dấu gạch ngang. Không dùng slug của route hệ thống.
   */
  slug: string;
  /**
   * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
   */
  featuredImage: number | Media;
  featuredImageAlt: string;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  legacyUpdatedAt: string;
  featured?: boolean | null;
  /**
   * Thông tin dùng cho kết quả tìm kiếm và Open Graph. Không thay đổi SEO production trong bước này.
   */
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tin tức và nội dung hướng dẫn của Tùng Phát.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  excerpt: string;
  category: string;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  author: string;
  relatedProducts?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedArticles?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown được giữ nguyên để tương thích dữ liệu và renderer hiện tại.
   */
  body: string;
  video?: (number | null) | Media;
  catalogue?: (number | null) | Media;
  /**
   * Chỉ chữ thường, số và dấu gạch ngang.
   */
  slug: string;
  /**
   * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
   */
  featuredImage: number | Media;
  featuredImageAlt: string;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  legacyUpdatedAt: string;
  featured?: boolean | null;
  /**
   * Thông tin dùng cho kết quả tìm kiếm và Open Graph. Không thay đổi SEO production trong bước này.
   */
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Dự án CNC đã được phép công bố. Không nhập thông tin nhận dạng khách hàng.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  materialType: string;
  processingType: string;
  thickness: string;
  /**
   * Không ghi địa chỉ khách hàng.
   */
  area?: string | null;
  workItems: {
    value: string;
    id?: string | null;
  }[];
  customerRequirement: string;
  process: {
    value: string;
    id?: string | null;
  }[];
  result: string;
  beforeImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  afterImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  completedAt: string;
  quoteCta: string;
  /**
   * Markdown được giữ nguyên để tương thích dữ liệu và renderer hiện tại.
   */
  body: string;
  video?: (number | null) | Media;
  catalogue?: (number | null) | Media;
  /**
   * Chỉ chữ thường, số và dấu gạch ngang.
   */
  slug: string;
  /**
   * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
   */
  featuredImage: number | Media;
  featuredImageAlt: string;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  legacyUpdatedAt: string;
  featured?: boolean | null;
  /**
   * Thông tin dùng cho kết quả tìm kiếm và Open Graph. Không thay đổi SEO production trong bước này.
   */
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Trang dịch vụ public ở route gốc; slug được kiểm tra để không đè route hệ thống.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  eyebrow: string;
  excerpt: string;
  materialTypes: {
    value: string;
    id?: string | null;
  }[];
  workItems: {
    value: string;
    id?: string | null;
  }[];
  process: {
    value: string;
    id?: string | null;
  }[];
  fileGuidance: {
    value: string;
    id?: string | null;
  }[];
  quoteCta: string;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown được giữ nguyên để tương thích dữ liệu và renderer hiện tại.
   */
  body: string;
  video?: (number | null) | Media;
  catalogue?: (number | null) | Media;
  /**
   * Chỉ chữ thường, số và dấu gạch ngang. Không dùng slug của route hệ thống.
   */
  slug: string;
  /**
   * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
   */
  featuredImage: number | Media;
  featuredImageAlt: string;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  legacyUpdatedAt: string;
  featured?: boolean | null;
  /**
   * Thông tin dùng cho kết quả tìm kiếm và Open Graph. Không thay đổi SEO production trong bước này.
   */
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    noindex?: boolean | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  stableKey: string;
  source: 'google' | 'managed';
  branchKey: string;
  reviewerName: string;
  reviewerPhotoURL?: string | null;
  rating: number;
  comment?: string | null;
  ownerReply?: string | null;
  reviewedAt?: string | null;
  published?: boolean | null;
  displayOrder?: number | null;
  sourcePayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gbp-connections".
 */
export interface GbpConnection {
  id: number;
  branchKey: string;
  projectID: string;
  accountName?: string | null;
  locationName?: string | null;
  locationTitle?: string | null;
  placeID?: string | null;
  accessTokenCiphertext?: string | null;
  refreshTokenCiphertext?: string | null;
  tokenExpiresAt?: string | null;
  status: 'not_configured' | 'connected' | 'error';
  lastSyncedAt?: string | null;
  lastErrorSafe?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  legacyID?: string | null;
  submissionKey: string;
  type: 'contact' | 'quote';
  fullName: string;
  phone: string;
  email?: string | null;
  company?: string | null;
  city?: string | null;
  product?: string | null;
  material?: string | null;
  thickness?: string | null;
  dimensions?: string | null;
  quantity?: string | null;
  cncRequirement?: string | null;
  message?: string | null;
  sourceURL?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  attribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost' | 'spam' | 'archived';
  consentAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  eventID: string;
  sessionID: string;
  visitorID: string;
  eventName: string;
  occurredAt: string;
  path: string;
  pageTitle?: string | null;
  contentType?: string | null;
  contentID?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isTest?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  source: string;
  destination: string;
  statusCode: '301' | '302' | '307' | '308';
  active?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'material-codes';
        value: number | MaterialCode;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'gbp-connections';
        value: number | GbpConnection;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaKind?: T;
  uploadedBy?: T;
  r2Key?: T;
  sourceURL?: T;
  checksum?: T;
  roomApplication?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  sourceURL?: T;
  enabled?: T;
  lastSyncedAt?: T;
  syncChecksum?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  supplier?: T;
  parent?: T;
  description?: T;
  sourceID?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-codes_select".
 */
export interface MaterialCodesSelect<T extends boolean = true> {
  stableKey?: T;
  supplier?: T;
  code?: T;
  name?: T;
  slug?: T;
  category?: T;
  subcategory?: T;
  description?: T;
  materialType?: T;
  finish?: T;
  dimensions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  thicknesses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  specifications?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  applicationGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  sourceURL?: T;
  sourceID?: T;
  syncChecksum?: T;
  lastSyncedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  excerpt?: T;
  materialType?: T;
  supplier?: T;
  thicknesses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  dimensions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  surfaces?:
    | T
    | {
        value?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        value?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  limitations?:
    | T
    | {
        value?: T;
        id?: T;
      };
  orderingSteps?:
    | T
    | {
        value?: T;
        id?: T;
      };
  availability?: T;
  quoteCta?: T;
  relatedArticles?:
    | T
    | {
        value?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  body?: T;
  video?: T;
  catalogue?: T;
  slug?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedAt?: T;
  legacyUpdatedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  category?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  author?: T;
  relatedProducts?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relatedArticles?:
    | T
    | {
        value?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  body?: T;
  video?: T;
  catalogue?: T;
  slug?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedAt?: T;
  legacyUpdatedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  materialType?: T;
  processingType?: T;
  thickness?: T;
  area?: T;
  workItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  customerRequirement?: T;
  process?:
    | T
    | {
        value?: T;
        id?: T;
      };
  result?: T;
  beforeImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  afterImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  completedAt?: T;
  quoteCta?: T;
  body?: T;
  video?: T;
  catalogue?: T;
  slug?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedAt?: T;
  legacyUpdatedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  eyebrow?: T;
  excerpt?: T;
  materialTypes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  workItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  process?:
    | T
    | {
        value?: T;
        id?: T;
      };
  fileGuidance?:
    | T
    | {
        value?: T;
        id?: T;
      };
  quoteCta?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  body?: T;
  video?: T;
  catalogue?: T;
  slug?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedAt?: T;
  legacyUpdatedAt?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        noindex?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  stableKey?: T;
  source?: T;
  branchKey?: T;
  reviewerName?: T;
  reviewerPhotoURL?: T;
  rating?: T;
  comment?: T;
  ownerReply?: T;
  reviewedAt?: T;
  published?: T;
  displayOrder?: T;
  sourcePayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gbp-connections_select".
 */
export interface GbpConnectionsSelect<T extends boolean = true> {
  branchKey?: T;
  projectID?: T;
  accountName?: T;
  locationName?: T;
  locationTitle?: T;
  placeID?: T;
  accessTokenCiphertext?: T;
  refreshTokenCiphertext?: T;
  tokenExpiresAt?: T;
  status?: T;
  lastSyncedAt?: T;
  lastErrorSafe?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  legacyID?: T;
  submissionKey?: T;
  type?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  company?: T;
  city?: T;
  product?: T;
  material?: T;
  thickness?: T;
  dimensions?: T;
  quantity?: T;
  cncRequirement?: T;
  message?: T;
  sourceURL?: T;
  ipHash?: T;
  userAgent?: T;
  attribution?: T;
  status?: T;
  consentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventID?: T;
  sessionID?: T;
  visitorID?: T;
  eventName?: T;
  occurredAt?: T;
  path?: T;
  pageTitle?: T;
  contentType?: T;
  contentID?: T;
  metadata?: T;
  isTest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  source?: T;
  destination?: T;
  statusCode?: T;
  active?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Thông tin liên hệ, địa điểm và CTA dùng trên website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings".
 */
export interface BusinessSetting {
  id: number;
  businessName: string;
  displayName: string;
  taxId: string;
  website: string;
  phoneDisplay: string;
  phoneE164: string;
  zaloUrl: string;
  email?: string | null;
  openingHours?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  serviceAreas: {
    value: string;
    id?: string | null;
  }[];
  locations: {
    locationId: string;
    shortId: string;
    name: string;
    address: string;
    streetAddress: string;
    addressLocality: string;
    addressRegion: string;
    addressCountry: string;
    /**
     * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
     */
    image: number | Media;
    imageAlt: string;
    embedSrc: string;
    directionsUrl: string;
    id?: string | null;
  }[];
  socialLinks?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  footerDescription: string;
  primaryCtaLabel: string;
  primaryCtaUrl: string;
  localBusinessType?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Giá trị SEO dự phòng của website; không ghi đè SEO đã nhập ở từng nội dung.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  siteUrl: string;
  siteName: string;
  defaultTitle: string;
  defaultDescription: string;
  /**
   * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
   */
  defaultOgImage: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Nội dung ngắn của trang chủ, liên hệ và báo giá.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  legacyUpdatedAt: string;
  homeHeroDescription: string;
  contactIntro: string;
  quoteIntro: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Danh mục vật liệu đang dùng cho điều hướng và phân nhóm website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-categories".
 */
export interface MaterialCategory {
  id: number;
  title: string;
  items: {
    name: string;
    /**
     * Chỉ chữ thường, số và dấu gạch ngang.
     */
    slug: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Thương hiệu và catalogue được website giới thiệu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  items: {
    /**
     * Chỉ chữ thường, số và dấu gạch ngang.
     */
    slug: string;
    name: string;
    /**
     * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
     */
    logo?: (number | null) | Media;
    description: string;
    catalogues?:
      | {
          name: string;
          /**
           * Chọn ảnh từ Media; Alt text nằm ngay bên dưới để bảo đảm khả năng tiếp cận.
           */
          thumbnail?: (number | null) | Media;
          description?: string | null;
          pdf?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Giữ để đối chiếu migration; website hiện không có contract ổn định cho field này.
     */
    legacyProducts?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-settings_select".
 */
export interface BusinessSettingsSelect<T extends boolean = true> {
  businessName?: T;
  displayName?: T;
  taxId?: T;
  website?: T;
  phoneDisplay?: T;
  phoneE164?: T;
  zaloUrl?: T;
  email?: T;
  openingHours?:
    | T
    | {
        value?: T;
        id?: T;
      };
  serviceAreas?:
    | T
    | {
        value?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        locationId?: T;
        shortId?: T;
        name?: T;
        address?: T;
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        addressCountry?: T;
        image?: T;
        imageAlt?: T;
        embedSrc?: T;
        directionsUrl?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        value?: T;
        id?: T;
      };
  footerDescription?: T;
  primaryCtaLabel?: T;
  primaryCtaUrl?: T;
  localBusinessType?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteUrl?: T;
  siteName?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  legacyUpdatedAt?: T;
  homeHeroDescription?: T;
  contactIntro?: T;
  quoteIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-categories_select".
 */
export interface MaterialCategoriesSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        slug?: T;
        name?: T;
        logo?: T;
        description?: T;
        catalogues?:
          | T
          | {
              name?: T;
              thumbnail?: T;
              description?: T;
              pdf?: T;
              id?: T;
            };
        legacyProducts?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}