/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cms-oauth/wrangler.jsonc --include-runtime=false --strict-vars=false workers/cms-oauth/worker-configuration.d.ts` (hash: 11245551118fd10f2afdf664b9e0e766)
interface __BaseEnv_Env {
	CMS_ORIGIN: string;
	CMS_SITE_ID: string;
	OAUTH_CALLBACK_URL: string;
	GITHUB_REPO_PRIVATE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CMS_ORIGIN" | "CMS_SITE_ID" | "OAUTH_CALLBACK_URL" | "GITHUB_REPO_PRIVATE">> {}
}
