/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareCmsEnv` (hash: e079f55f3787f641cb884e60d7a4b2fb)
interface __BaseEnv_CloudflareCmsEnv {
	DB: D1Database;
	ENVIRONMENT: string;
	CORS_ALLOWED_ORIGINS: string;
	CORS_ALLOWED_ORIGIN_SUFFIXES: string;
	TURNSTILE_ALLOWED_HOSTNAMES: string;
	TURNSTILE_ALLOWED_HOSTNAME_SUFFIXES: string;
	TURNSTILE_EXPECTED_ACTION: string;
	CMS_ALLOWED_ORIGINS: string;
	CMS_SITE_IDS: string;
	OAUTH_CALLBACK_URL: string;
	OAUTH_ALLOWED_EMAIL: string;
	GITHUB_REPO_PRIVATE: string;
	TURNSTILE_SECRET_KEY: string;
	IP_HASH_SALT: string;
	GITHUB_OAUTH_ID: string;
	GITHUB_OAUTH_SECRET: string;
	OAUTH_STATE_SECRET: string;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		DB: D1Database;
		ENVIRONMENT: string;
		CORS_ALLOWED_ORIGINS: string;
		CORS_ALLOWED_ORIGIN_SUFFIXES: string;
		TURNSTILE_ALLOWED_HOSTNAMES: string;
		TURNSTILE_ALLOWED_HOSTNAME_SUFFIXES: string;
		TURNSTILE_EXPECTED_ACTION: string;
		CMS_ALLOWED_ORIGINS: string;
		CMS_SITE_IDS: string;
		OAUTH_CALLBACK_URL: string;
		OAUTH_ALLOWED_EMAIL: string;
		GITHUB_REPO_PRIVATE: string;
		TURNSTILE_SECRET_KEY: string;
		IP_HASH_SALT: string;
		GITHUB_OAUTH_ID: string;
		GITHUB_OAUTH_SECRET: string;
		OAUTH_STATE_SECRET: string;
	}
	interface Env extends __BaseEnv_CloudflareCmsEnv {}
}
interface CloudflareCmsEnv extends __BaseEnv_CloudflareCmsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CORS_ALLOWED_ORIGINS" | "CORS_ALLOWED_ORIGIN_SUFFIXES" | "TURNSTILE_ALLOWED_HOSTNAMES" | "TURNSTILE_ALLOWED_HOSTNAME_SUFFIXES" | "TURNSTILE_EXPECTED_ACTION" | "CMS_ALLOWED_ORIGINS" | "CMS_SITE_IDS" | "OAUTH_CALLBACK_URL" | "OAUTH_ALLOWED_EMAIL" | "GITHUB_REPO_PRIVATE" | "TURNSTILE_SECRET_KEY" | "IP_HASH_SALT" | "GITHUB_OAUTH_ID" | "GITHUB_OAUTH_SECRET" | "OAUTH_STATE_SECRET">> {}
}
